CREATE DATABASE IF NOT EXISTS blog;
USE blog;

CREATE TABLE usuario
(
id int not null AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
senha CHAR(60) NOT NULL,
data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ativo TINYINT(4) NOT NULL DEFAULT '0',
adm TINYINT(4) NOT NULL DEFAULT '0'
);

CREATE TABLE post
(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
titulo VARCHAR(255) NOT NULL,
texto TEXT NOT NULL,
usuario_id INT NOT NULL,
data_criacao DATETIME NOT NULL,
data_postagem DATETIME NOT NULL,

FOREIGN KEY(usuario_id) REFERENCES usuario(id)
);

INSERT INTO usuario (nome, email, senha, ativo, adm)
VALUES ('Maria', 'maria@gmail.com', '12345678', 1, 0);
